module.exports = [

{
    id:            122,
    name:          `Beer`,
    grade:         1,
    icon:          `/items/new_icon/03_etc/07_productmaterial/00009213.png`,
    type:          `Recipe`,
    r_type:        `Cooking`,
    skill_lvl:     `Beginner 1`,
    materials: [{
        amount:        5,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00007005.png`,
        link:          `/us/materialgroup/1/`,
        name:          `Cereals`,
        id:            1,
    }, {
        amount:        6,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009059.png`,
        link:          `/us/item/9059/`,
        name:          `Mineral Water`,
        id:            9059,
    }, {
        amount:        1,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009002.png`,
        link:          `/us/item/9002/`,
        name:          `Sugar`,
        id:            9002,
    }, {
        amount:        2,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009005.png`,
        link:          `/us/item/9005/`,
        name:          `Leavening Agent`,
        id:            9005,
    }],
    results: [{
        amount:        1,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009213.png`,
        link:          `/us/item/9213/`,
        name:          `Beer`,
        id:            9213,
    }, {
        amount:        1,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009283.png`,
        link:          `/us/item/9283/`,
        name:          `Cold Draft Beer`,
        id:            9283,
    }, ]
},

{
    id:            169,
    name:          `Balenos Meal`,
    grade:         3,
    icon:          `/items/new_icon/03_etc/07_productmaterial/00009601.png`,
    type:          `Recipe`,
    r_type:        `Cooking`,
    skill_lvl:     `Skilled 6`,
    materials: [{
        amount:        1,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009203.png`,
        link:          `/us/item/9203/`,
        name:          `Cheese Gratin`,
        id:            9203,
    }, {
        amount:        1,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009404.png`,
        link:          `/us/item/9404/`,
        name:          `Meat Croquette`,
        id:            9404,
    }, {
        amount:        1,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009417.png`,
        link:          `/us/item/9417/`,
        name:          `Smoked Fish Steak`,
        id:            9417,
    }, {
        amount:        2,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009241.png`,
        link:          `/us/item/9241/`,
        name:          `Stir-Fried Vegetables`,
        id:            9241,
    }, {
        amount:        2,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009213.png`,
        link:          `/us/item/9213/`,
        name:          `Beer`,
        id:            9213,
    }],
    results: [{
        amount:        1,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009601.png`,
        link:          `/us/item/9601/`,
        name:          `Balenos Meal`,
        id:            9601,
    }, {
        amount:        1,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009602.png`,
        link:          `/us/item/9602/`,
        name:          `Special Balenos Meal`,
        id:            9602,
    }, ],
},

{
    id:            129,
    name:          `Soft Bread`,
    grade:         1,
    icon:          `/items/new_icon/03_etc/07_productmaterial/00009260.png`,
    type:          `Recipe`,
    r_type:        `Cooking`,
    skill_lvl:     `Beginner 6`,
    materials: [{
        amount:        6,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00007205.png`,
        link:          `/us/materialgroup/2/`,
        name:          `Dough`,
        id:            2,
    }, {
        amount:        2,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009005.png`,
        link:          `/us/item/9005/`,
        name:          `Leavening Agent`,
        id:            9005,
    }, {
        amount:        2,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009064.png`,
        link:          `/us/item/9064/`,
        name:          `Egg`,
        id:            9064,
    }, {
        amount:        3,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009065.png`,
        link:          `/us/item/9065/`,
        name:          `Milk`,
        id:            9065,
    }, ],
    results: [{
        amount:        1,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009260.png`,
        link:          `/us/item/9260/`,
        name:          `Soft Bread`,
        id:            9260,
    }, {
        amount:        1,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00009286.png`,
        link:          `/us/item/9286/`,
        name:          `Moist Milk Bread`,
        id:            9286,
    }, ],
},

{
    id:            27,
    name:          `Defense Elixir`,
    grade:         1,
    icon:          `/items/new_icon/03_etc/08_potion/00000716.png`,
    type:          `Recipe`,
    r_type:        `Alchemy`,
    skill_lvl:     `Beginner 1`,
    materials: [{
        amount:        1,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00005301.png`,
        link:          `/us/item/5301/`,
        name:          `Clear Liquid Reagent`,
        id:            5301,
    }, {
        amount:        6,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00005001.png`,
        link:          `/us/item/5001/`,
        name:          `Ash Sap`,
        id:            5001,
    }, {
        amount:        5,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00006205.png`,
        link:          `/us/materialgroup/17/`,
        name:          `Blood 2`,
        id:            17,
    }, {
        amount:        3,
        icon:          `/items/new_icon/03_etc/07_productmaterial/00006656.png`,
        link:          `/us/item/6656/`,
        name:          `Purified Water`,
        id:            6656,
    }],
    results: [{
        amount:        1,
        icon:          `/items/new_icon/03_etc/08_potion/00000716.png`,
        link:          `/us/item/716/`,
        name:          `Defense Elixir`,
        id:            716,
    }, {
        amount:        1,
        icon:          `/items/new_icon/03_etc/08_potion/00000717.png`,
        link:          `/us/item/717/`,
        name:          `Elixir of Steel Defense`,
        id:            717,
    }, ],
},

]